"""Fake TLS handshake (ee-secret) — used to disguise MTProto as HTTPS.

This is the proxy server side: we accept a TLS ClientHello, verify it was
generated by a Telegram client that knows our secret, reply with a forged
ServerHello, then expose a tiny stream wrapper that strips TLS record
framing from application data.
"""
from __future__ import annotations

import asyncio
import hmac
import hashlib
import logging
import os
import random
import struct
import time
from typing import Optional, Tuple

from .constants import (
    CLIENT_RANDOM_LEN,
    CLIENT_RANDOM_OFFSET,
    SESSION_ID_LEN,
    SESSION_ID_OFFSET,
    TIMESTAMP_TOLERANCE,
    TLS_APPDATA_MAX,
    TLS_RECORD_APPDATA,
    TLS_RECORD_CCS,
    TLS_RECORD_HANDSHAKE,
)

log = logging.getLogger("tgwsproxy.fake_tls")

_CCS_FRAME = b"\x14\x03\x03\x00\x01\x01"

_SERVER_HELLO_TEMPLATE = bytearray(
    b"\x16\x03\x03\x00\x7a"
    b"\x02\x00\x00\x76"
    b"\x03\x03"
    + b"\x00" * 32  # server_random — filled in later
    + b"\x20"
    + b"\x00" * 32  # session_id echo
    + b"\x13\x01\x00"
    + b"\x00\x2e"
    + b"\x00\x33\x00\x24\x00\x1d\x00\x20"
    + b"\x00" * 32  # x25519 pubkey
    + b"\x00\x2b\x00\x02\x03\x04"
)
_SH_RANDOM_OFFSET = 11
_SH_SESSION_OFFSET = 44
_SH_PUBKEY_OFFSET = 89


def verify_client_hello(
    data: bytes, secret: bytes
) -> Optional[Tuple[bytes, bytes, int]]:
    """Return (client_random, session_id, timestamp) if HELLO is authentic."""
    if len(data) < 43:
        return None
    if data[0] != TLS_RECORD_HANDSHAKE or data[5] != 0x01:
        return None

    client_random = bytes(
        data[CLIENT_RANDOM_OFFSET : CLIENT_RANDOM_OFFSET + CLIENT_RANDOM_LEN]
    )

    zeroed = bytearray(data)
    zeroed[
        CLIENT_RANDOM_OFFSET : CLIENT_RANDOM_OFFSET + CLIENT_RANDOM_LEN
    ] = b"\x00" * CLIENT_RANDOM_LEN

    expected = hmac.new(secret, bytes(zeroed), hashlib.sha256).digest()
    if not hmac.compare_digest(expected[:28], client_random[:28]):
        return None

    ts_xor = bytes(client_random[28 + i] ^ expected[28 + i] for i in range(4))
    timestamp = struct.unpack("<I", ts_xor)[0]
    if abs(int(time.time()) - timestamp) > TIMESTAMP_TOLERANCE:
        return None

    session_id = b"\x00" * SESSION_ID_LEN
    if (
        len(data) >= SESSION_ID_OFFSET + SESSION_ID_LEN
        and data[43] == SESSION_ID_LEN
    ):
        session_id = bytes(
            data[SESSION_ID_OFFSET : SESSION_ID_OFFSET + SESSION_ID_LEN]
        )

    return client_random, session_id, timestamp


def build_server_hello(
    secret: bytes, client_random: bytes, session_id: bytes
) -> bytes:
    """Forge a ServerHello + dummy AppData that matches the client's HMAC."""
    hello = bytearray(_SERVER_HELLO_TEMPLATE)
    hello[_SH_SESSION_OFFSET : _SH_SESSION_OFFSET + 32] = session_id
    hello[_SH_PUBKEY_OFFSET : _SH_PUBKEY_OFFSET + 32] = os.urandom(32)

    appdata_size = random.randint(1900, 2100)
    appdata = os.urandom(appdata_size)
    app_record = (
        b"\x17\x03\x03" + struct.pack(">H", appdata_size) + appdata
    )

    response = bytes(hello) + _CCS_FRAME + app_record

    server_random = hmac.new(
        secret, client_random + response, hashlib.sha256
    ).digest()
    final = bytearray(response)
    final[_SH_RANDOM_OFFSET : _SH_RANDOM_OFFSET + 32] = server_random
    return bytes(final)


def wrap_tls_records(data: bytes) -> bytes:
    """Chop a buffer into TLS Application Data records of <=16KB each."""
    parts = []
    for offset in range(0, len(data), TLS_APPDATA_MAX):
        chunk = data[offset : offset + TLS_APPDATA_MAX]
        parts.append(b"\x17\x03\x03" + struct.pack(">H", len(chunk)) + chunk)
    return b"".join(parts)


class FakeTlsStream:
    """Stream-like wrapper that hides TLS record framing.

    Reads strip TLS app-data record headers; writes wrap data into records.
    """

    __slots__ = ("_reader", "_writer", "_pending", "_record_left")

    def __init__(
        self, reader: asyncio.StreamReader, writer: asyncio.StreamWriter
    ):
        self._reader = reader
        self._writer = writer
        self._pending = bytearray()
        self._record_left = 0

    async def readexactly(self, n: int) -> bytes:
        while len(self._pending) < n:
            chunk = await self._read_record_chunk()
            if not chunk:
                raise asyncio.IncompleteReadError(bytes(self._pending), n)
            self._pending.extend(chunk)
        out = bytes(self._pending[:n])
        del self._pending[:n]
        return out

    async def read(self, n: int) -> bytes:
        if self._pending:
            out = bytes(self._pending[:n])
            del self._pending[:n]
            return out
        chunk = await self._read_record_chunk()
        if not chunk:
            return b""
        if len(chunk) > n:
            self._pending.extend(chunk[n:])
            return chunk[:n]
        return chunk

    async def _read_record_chunk(self) -> bytes:
        """Return at most one record's worth of bytes; handles fragments."""
        if self._record_left > 0:
            chunk = await self._reader.read(self._record_left)
            if not chunk:
                return b""
            self._record_left -= len(chunk)
            return chunk

        while True:
            header = await self._reader.readexactly(5)
            rec_type = header[0]
            rec_len = struct.unpack(">H", header[3:5])[0]

            if rec_type == TLS_RECORD_CCS:
                if rec_len > 0:
                    await self._reader.readexactly(rec_len)
                continue

            if rec_type != TLS_RECORD_APPDATA:
                return b""

            chunk = await self._reader.read(min(rec_len, 65536))
            if not chunk:
                return b""
            remaining = rec_len - len(chunk)
            if remaining > 0:
                self._record_left = remaining
            return chunk

    def write(self, data: bytes) -> None:
        self._writer.write(wrap_tls_records(data))

    async def drain(self) -> None:
        await self._writer.drain()

    def close(self) -> None:
        self._writer.close()

    async def wait_closed(self) -> None:
        await self._writer.wait_closed()

    def get_extra_info(self, name, default=None):
        return self._writer.get_extra_info(name, default)

    @property
    def transport(self):
        return self._writer.transport

    def is_closing(self):
        return self._writer.is_closing()


async def relay_to_masking_domain(
    reader: asyncio.StreamReader,
    writer: asyncio.StreamWriter,
    initial: bytes,
    domain: str,
    label: str,
) -> None:
    """Tunnel the client to a real HTTPS site when Fake-TLS auth fails."""
    try:
        upstream_reader, upstream_writer = await asyncio.wait_for(
            asyncio.open_connection(domain, 443), timeout=10
        )
    except Exception as exc:
        log.warning("[%s] masking: cannot reach %s: %s", label, domain, exc)
        return

    log.debug("[%s] masking -> %s:443", label, domain)
    try:
        if initial:
            upstream_writer.write(initial)
            await upstream_writer.drain()

        async def pipe(src, dst):
            try:
                while True:
                    chunk = await src.read(16384)
                    if not chunk:
                        break
                    dst.write(chunk)
                    await dst.drain()
            except (ConnectionError, OSError, asyncio.CancelledError):
                pass
            finally:
                try:
                    dst.close()
                    await dst.wait_closed()
                except Exception:
                    pass

        await asyncio.gather(
            pipe(reader, upstream_writer), pipe(upstream_reader, writer)
        )
    finally:
        try:
            upstream_writer.close()
        except Exception:
            pass
